version: 2
workflows:
  version: 2
  test:
    jobs:
      - tox

jobs:
  tox:
    docker:
      - image: python:3.7-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            apt-get -qq update && apt-get -y -qq install libtag1-dev python-dev python3-dev virtualenv python3-virtualenv
            virtualenv --python=python3 venv
            . venv/bin/activate
            pip install tox
      - save_cache:
          paths:
            - ./venv
            - ./.tox
          key: v1-dependencies-
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox